import { LayoutGroup, motion, useReducedMotion } from 'motion/react'
import { KeyboardEvent } from 'react'
import './JellyRadio.css'

export type JellyRadioItem = { value: string; label: string; disabled?: boolean }
type JellyRadioProps = { items: JellyRadioItem[]; value?: string; defaultValue?: string; onValueChange?: (value: string) => void; chipColor?: string; activeColor?: string; textColor?: string; activeTextColor?: string; size?: 'sm' | 'md'; gap?: number; radius?: number; swell?: number; barge?: number; shrink?: number; jelly?: number; bounce?: number; stagger?: number; stiffness?: number }

export function JellyRadio({ items, value, defaultValue, onValueChange, chipColor = '#27272a', activeColor = '#f5f5f5', textColor = '#f5f5f5', activeTextColor = '#18181b', size = 'md', gap = 5, radius = 18, swell = 0.16, barge = 5, shrink = 0.04, jelly = 0.8, bounce = 0.22, stagger = 18, stiffness = 580 }: JellyRadioProps) {
  const reducedMotion = useReducedMotion(); const selected = value ?? defaultValue ?? items[0]?.value
  const choose = (next: string) => onValueChange?.(next)
  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { if (!['ArrowRight', 'ArrowLeft', 'ArrowDown', 'ArrowUp'].includes(event.key)) return; event.preventDefault(); const direction = event.key === 'ArrowRight' || event.key === 'ArrowDown' ? 1 : -1; const next = (index + direction + items.length) % items.length; choose(items[next].value); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role="radio"]')[next]?.focus() }
  return <LayoutGroup><div className={`jelly-radio jelly-radio--${size}`} role="radiogroup" aria-label="Portfolio sections" style={{ '--jelly-gap': `${gap}px`, '--jelly-radius': `${radius}px`, '--jelly-chip': chipColor, '--jelly-active': activeColor, '--jelly-text': textColor, '--jelly-active-text': activeTextColor } as React.CSSProperties}>{items.map((item, index) => { const active = item.value === selected; return <motion.button key={item.value} className="jelly-radio__item" type="button" role="radio" aria-checked={active} aria-disabled={item.disabled} tabIndex={active ? 0 : -1} disabled={item.disabled} onKeyDown={(event) => onKeyDown(event, index)} onClick={() => choose(item.value)} whileTap={reducedMotion ? undefined : { scale: 1 - shrink }} transition={{ type: 'spring', stiffness, damping: 28 }}><span className="jelly-radio__label">{item.label}</span>{active && <motion.span className="jelly-radio__active" layoutId="jelly-radio-active" initial={reducedMotion ? false : { opacity: 0, scale: 1 - swell, y: -barge }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ type: 'spring', stiffness, damping: Math.max(16, 34 - jelly * 10), bounce }}><motion.span className="jelly-radio__active-label" initial={reducedMotion ? false : { y: stagger * 0.08 }} animate={{ y: 0 }} transition={{ type: 'spring', stiffness, damping: 24 }}>{item.label}</motion.span></motion.span>}</motion.button> })}</div></LayoutGroup>
}
